### ISSUE TITLE
Tasksystem

### ISSUE THREAD

**Issue by flaver12** [Project-Tacoma/PublicMission#12]
- Create Mainmission
- Create X Sidemission
- Possibility to add reward
- Add difficulty settings

**Comment by erenior** [comment]
Überlegung:
Sidemissions machen die Mainmission "einfacher". // sollten Storytechnisch sinnvoll passen
Erfolgreicher Abschluss der Mainmissionen bringt Tickets wieder (Reward: Tickets)

Meinungen?

**Comment by flaver12** [comment]
`

    class pms_exmapleTask1 {

    name = "Example"; //Name of the task
    desc = "Example desc"; // Description of the task
    markerName = "pms_exampleTask1"; // The name of the empty marker that you have given in the mission
    taskType = "kill"; //https://community.bistudio.com/wiki/Arma_3_Tasks_Overhaul#Default_Task_Types:_Actions
    reward = 20 //How many tickets they get for this`

Wie hier zu sehen ist es bereits intergriert, dass man tickets bekommt.
Naja Sidemissions können ja auch Tickets als Reward haben bzw irgend eine art von Reward

**Comment by erenior** [comment]
Welche Art von reward außer tickets wäre denn sinnvoll? Oder reden wir hier von reward im sinne von medailliensystem?

**Comment by flaver12** [comment]
Nein wir reden nicht an einander vorbei. Ist nur der Name im system der so heisst.
Hmm Fahrzeuge oder auch das ka z.b. Slots unlocked werden, wenn man ka eine Artybase eingenommen hat werden die Mörserslots unlocked oder sowas in der Richtung.
Denke da kann man Creative werden.
