### ISSUE TITLE
Anzahl Gegner abhängig von Anzahl Spielern

### ISSUE THREAD

**Issue by erenior** [Project-Tacoma/PublicMission#22]
Die Schwierigkeit sollte irgendwie vom System gestellt werden. Wenn nur wenige Spieler unterwegs sind macht es wenig Sinn den Spielern drölf Panzer vor die Nase zu setzen. Kann man irgendwie per Script eine Prüfung vornehmen wir "stark" BLUFOR gerade präsent ist, sei es nun insgesamt auf der MAP oder in einem Umkreis um eine Mission herum... geht das?

**Comment by flaver12** [comment]
Jaa ist technisch lösbar

**Comment by Leovinus86** [comment]
Dafür dachte ich ja eigentlich an die 3 Regionen mit den 3 unterschiedlich starken Streitkrãften. Oder soll das ein zusätzlicher Faktor sein? (Also nach dem Motto: 1x Nationalgarde = 2x ISIS = 3x Miliz)

**Comment by flaver12** [comment]
Issue gibts schon #15
