### ISSUE TITLE
Russisches Equip, ja oder nein?

### ISSUE THREAD

**Issue by Leovinus86** [Project-Tacoma/PublicMission#23]
Wie schon in Discord beschrieben, hatte ich mir überlegt, ob wir evtl. Russen oder Partisanen auf Blufor-Seite einbauen sollten, um die Spieler zu locken, die gerne mit russischem Equip rumlaufen wollen. Bei den Russen wäre das equiptechnisch einfach, weil sich das optisch besser vom Opforkram abhebt. Bei Partisanen wäre es storytechnisch einfacher.

**Comment by flaver12** [comment]
Ich bin dafür. Ich mag russen Waffen und Fahrzeuge. Allerdings hast du da wieder das Problem der in BW-Flecktran rumrennende Spieler mit der AK

**Comment by erenior** [comment]
bin da sehr gespaltener meinung. auf der einen seite hätte ich nichts dagegen, wenn jemand russen spielen will... auf der anderen seite, dann kommen wie flaver sagte irgendwelche leute auf bw+ak oder sowas. auch denkbar wäre, dass einige jammern, weil ja die waffen der gegner dann oft genau so klingen.
vom szenario her dachte ich eigentlich, es handelt sich eher um "westliche welt gegen die bösen muselköppe" oder sowas in der art

**Comment by Leovinus86** [comment]
Also ist pbw und niarsenal g36 auch draußen...?

**Comment by erenior** [comment]
carmine, du erinnerst mich in deiner argumentationsweise gerne mal an meine schwiegermutter. was hat denn z.b. das g36 jetzt genau damit zu tun?

**Comment by FleXteR1337** [comment]
Ich denke wie bei so vielen kommt es auf die Playerbase an, wenn der Zugeführt/Sql festlegt das das Team als russische Spetznatz ausrückt, dann hat sich das Team daran zuhalten!?
Ich persönlich bin kein Freund von russ. Infantrieeinheiten/Equipment, ganz anders sieht es da bei den Air-Assets aus und ich fänd es schon cool mal ne SU-25 zu sehen anstatt eine A10....mal ganz abgesehen davon das ich sie gern selber fliege😅

Aber wie am Anfang angesprochen, müssen wir uns darauf "verlassen können", dass die Playerbase da in unseren Sinne handelt und da kommt wieder das Problem ins Spiel es ist ein public!
Man könnte es höchstens in den Slots in der Lobby gleich festlegen? Und die Waffen entsprechend restriktieren, was wieder ne Menge tippen beinhaltet....

**Comment by erenior** [comment]
Ich entscheide erstmal wie folgt:
Russische Ausrüstung für Spieler bleibt erstmal draussen. Möglicherweise werde ich diese Entscheidung später nochmal revidieren.
Ich sehe grundsätzlich erstmal die Verwechslungsgefahr im Feld schwerwiegender als die zusätzliche Abwechslung.
