### ISSUE TITLE
VVS

### ISSUE THREAD

**Issue by flaver12** [Project-Tacoma/PublicMission#25]

**Comment by Leovinus86** [comment]
Sortierte Liste der Vehicle Classnames (VANILLA und RHS) und deren Kategorien. Evtl. müssen die Kategorien APC, IFV, MBT, ARTILLERY und AAA zusammengefasst werden um eine bessere Übersicht zu gewährleisten.

//CAR
"B_Quadbike_01_F",
"rhsusf_mrzr4_d",																			
"C_Offroad_01_F",
"B_G_Offroad_01_armed_F",													
"I_C_Offroad_02_unarmed_F",																	
"B_CTRG_LSV_01_light_F",
"B_T_LSV_01_unarmed_F",
"B_T_LSV_01_armed_F",						
"rhsusf_m1025_d",
"rhsusf_m1025_d_m2",
"rhsusf_m1025_d_Mk19",
"rhsusf_m998_d_2dr",				
"rhsusf_m998_d_2dr_halftop",
"rhsusf_m998_d_2dr_fulltop",
"rhsusf_m998_d_4dr",
"rhsusf_m998_d_4dr_halftop",
"rhsusf_m998_d_4dr_fulltop",

//TRUCK
"rhsusf_M1078A1P2_D_fmtv_usarmy",					
"rhsusf_M1078A1P2_B_M2_D_fmtv_usarmy",
"rhsusf_M1078A1P2_B_D_CP_fmtv_usarmy",
"rhsusf_M1084A1P2_D_fmtv_usarmy",
"rhsusf_M1084A1P2_B_M2_D_fmtv_usarmy",
"rhsusf_M1085A1P2_B_D_Medical_fmtv_usarmy",
"B_Truck_01_transport_F",
"B_Truck_01_covered_F",
"rhsusf_M1078A1R_SOV_M2_D_fmtv_socom",
"rhsusf_M1084A1R_SOV_M2_D_fmtv_socom",

//UTILITY VEHICLES
"I_MRAP_03_F",	
"B_APC_Tracked_01_CRV_F",
"rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_d",
"rhsusf_M977A4_AMMO_BKIT_M2_usarmy_d",
"rhsusf_M978A4_BKIT_usarmy_d",
"B_Truck_01_medical_F",
"B_Truck_01_Repair_F",
"B_Truck_01_fuel_F",
"B_Truck_01_ammo_F",

//MRAP										
"B_MRAP_01_F",
"B_MRAP_01_hmg_F",
"B_MRAP_01_gmg_F",	
"rhsusf_rg33_usmc_d",
"rhsusf_rg33_m2_usmc_d",
"rhsusf_M1117_D",																			
"rhsusf_M1220_usarmy_d",
"rhsusf_M1220_M153_M2_usarmy_d",
"rhsusf_M1220_M2_usarmy_d",
"rhsusf_M1220_MK19_usarmy_d",
"rhsusf_M1230_M2_usarmy_d",
"rhsusf_M1230_MK19_usarmy_d",
"rhsusf_M1230a1_usarmy_d",
"rhsusf_M1232_usarmy_d",
"rhsusf_M1232_M2_usarmy_d",
"rhsusf_M1232_MK19_usarmy_d",
"rhsusf_M1237_M2_usarmy_d",
"rhsusf_M1237_MK19_usarmy_d",

//APC
"B_APC_Tracked_01_rcws_F",																																		

//IFV
"B_APC_Wheeled_01_cannon_F",																				
"RHS_M2A2",
"RHS_M2A2_BUSKI",
"RHS_M2A3",
"RHS_M2A3_BUSKI",
"RHS_M2A3_BUSKIII",

//MBT
"rhsusf_m1a1aimd_usarmy",
"rhsusf_m1a1aim_tuski_d",
"rhsusf_m1a2sep1d_usarmy",
"rhsusf_m1a2sep1tuskid_usarmy",
"rhsusf_m1a2sep1tuskiid_usarmy",
"B_MBT_01_cannon_F",
"B_MBT_01_TUSK_F",														
	
//ARTILLERY																		
"B_MBT_01_mlrs_F",
"B_MBT_01_arty_F",
"rhsusf_m109d_usarmy",

//AAA
"RHS_M6",	
"B_APC_Tracked_01_AA_F",

//HELICOPTER
"RHS_MELB_H6M",
"RHS_MELB_MH6M",
"RHS_MELB_AH6M",
"B_Heli_Light_01_F",																		
"RHS_UH1Y_d",
"RHS_UH1Y_UNARMED_d",
"RHS_UH1Y_FFAR_d",
"RHS_UH60M_d",																				
"RHS_UH60M2_d",
"RHS_UH60M_ESSS_d",
"RHS_UH60M_ESSS2_d",
"RHS_UH60M_MEV_d",
"RHS_UH60M_MEV2_d",
"RHS_CH_47F_light",
"RHS_AH1Z",
"RHS_AH64DGrey",	
"RHS_AH64D",
"B_Heli_Light_01_dynamicLoadout_F",
"I_Heli_light_03_unarmed_F",
"I_Heli_light_03_dynamicLoadout_F",								
"B_Heli_Transport_01_camo_F",																
"B_Heli_Transport_03_unarmed_F",
"B_Heli_Transport_03_F",								
"B_Heli_Attack_01_dynamicLoadout_F",		

//PLANE
"rhsusf_f22",
"RHS_A10",												
"RHS_C130J",
"B_Plane_CAS_01_dynamicLoadout_F",	
"B_Plane_Fighter_01_F",
"B_Plane_Fighter_01_Stealth_F",	
"B_T_VTOL_01_infantry_F",
"B_T_VTOL_01_vehicle_F",
"B_T_VTOL_01_armed_F",						

//Maritime
"C_Scooter_transport_01_F",																	
"B_Boat_Transport_01_F",																	
"I_C_Boat_Transport_02_F",																	
"B_Boat_Armed_01_minigun_F",										
"B_SDV_01_F",
"rhsusf_mkvsoc",																			

//UAV
"B_UAV_06_F",
"B_UAV_06_medical_F",															
"B_UAV_01_F",
"IB_B_UAV_01_F",																
"B_UGV_01_F",															
"B_T_UAV_03_F",																				
"B_UAV_02_dynamicLoadout_F",
"B_UAV_02_CAS_F",												
"B_UAV_05_F",																				

//SUPPLY
"ACE_Wheel",
"ACE_Track",
"Land_PlasticCase_01_small_F",			
"ACE_medicalSupplyCrate_advanced",
"ACE_ConcertinaWireCoil",
"RoadCone_F",
"RoadBarrier_F",
"Land_PortableLight_single_F",
"RHS_M2StaticMG_MiniTripod_D",
"RHS_M2StaticMG_D",
"RHS_MK19_TriPod_D",
"RHS_TOW_TriPod_D",
"RHS_Stinger_AA_pod_D",
"B_static_AT_F","B_static_AA_F",
"B_Mortar_01_F",
"RHS_M252_D"

**Comment by Leovinus86** [comment]
Hinzufügen:

- Anzeige der Ticketkosten hinter dem Fahrzeugnamen
- Ein Despawn-button im Menü, und/oder
- Automatischer Despawn des Fahrzeugs nach kurzer Zeit

Entfernen:

- Marker an Spawner-Position setzen

**Comment by flaver12** [comment]
Frage: Hast du das mit Bones gemacht? Wennja habt ihr es gleich ins Framework integriert?

**Comment by Leovinus86** [comment]
Ist noch nicht passiert. Sind aber Punkte die früher oder später unbedingt einfließen sollten. Wir müssen ja auch bspw. erstmal überlegen, wie teuer die Fahrzeuge überhaupt werden sollen.

**Comment by flaver12** [comment]
So da von der technischen Umsetzung noch nichts passiert ist , werde ich das mal mir zuweisen.
