### ISSUE TITLE
Missiontypes Definition

### ISSUE THREAD

**Issue by flaver12** [Project-Tacoma/PublicMission#30]
Verschieden Missionstypen wie: "Zerstöre X", "Erobere Y" etc.

**Comment by Leovinus86** [comment]
Destroy/Steal Object
Capture/Kill HVT
Conquer/Defend/Patrol/Scout AO
Free/Escort VIP/POW
Defuse IED/Bomb
Transport Supplies

**Comment by erenior** [comment]
- Destroy Radio Tower
- Disarm Explosive Device (von IEDs bis hin zur atomaren Bedrohung?)
- Rescue Hostages
- Capture specific point on Map (AI Base)
- Secure Intel (and Transport to Base)
- Destroy Enemy Convoi
- Defend specific Point on Map
- Sabotage Generator
- Eliminate HVT
- Disable Mine Field
- Transport and deploy food to civilians
- Destroy Anti-Air
- Capture enemy vehicle
- Destroy enemy weapon crate
- Kidnap HVT

Überschneidungen mit Carmine möglich.
